// Builds the bundle's two indexes from every mods/*/.claude-plugin/plugin.json:
//   .claude-plugin/marketplace.json   what `claude plugin marketplace add` reads
//   mods/kozmos/hooks/catalog.ts      what the /kozmos hub lists
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// Where each mod draws, and its display title. Unknown mods fall back to "extra".
export const META = {
  kozmos: ['hub', 'Kozmos Hub'],
  bridge: ['pane', 'Bridge'],
  heartline: ['band', 'Heartline'],
  orrery: ['band', 'Orrery'],
  glyphfall: ['band', 'Glyphfall'],
  aurora: ['band', 'Aurora'],
  throttle: ['band', 'Throttle'],
  blackbox: ['band', 'Blackbox'],
  questline: ['band', 'Questline'],
  halo: ['band', 'Halo'],
  skies: ['band', 'Skies'],
  clawdling: ['companion', 'Clawdling'],
  laurels: ['companion', 'Laurels'],
  tempo: ['companion', 'Tempo'],
  epilogue: ['companion', 'Epilogue'],
  resonance: ['sound', 'Resonance'],
  hivemind: ['pane', 'Hivemind'],
  taskforge: ['pane', 'Taskforge'],
  chronicle: ['pane', 'Chronicle'],
  gearbox: ['pane', 'Gearbox'],
  tokenomics: ['pane', 'Tokenomics'],
  hourglass: ['pane', 'Hourglass'],
  spectra: ['pane', 'Spectra'],
  mosaic: ['pane', 'Mosaic'],
  gitscope: ['pane', 'Gitscope'],
  vitals: ['pane', 'Vitals'],
  thermal: ['pane', 'Thermal'],
  marquee: ['status', 'Marquee'],
  // Wave 2
  stamp: ['transcript', 'Stamp'],
  mantra: ['transcript', 'Mantra'],
  toolmarks: ['transcript', 'Toolmarks'],
  compass: ['transcript', 'Compass'],
  warpdrive: ['band', 'Warpdrive'],
  tidewater: ['band', 'Tidewater'],
  verdict: ['band', 'Verdict'],
  storyboard: ['band', 'Storyboard'],
  lofi: ['sound', 'Lofi'],
  switchboard: ['pane', 'Switchboard'],
  terminus: ['pane', 'Terminus'],
  breadcrumbs: ['pane', 'Breadcrumbs'],
  faultline: ['pane', 'Faultline'],
  relay: ['pane', 'Relay'],
  almanac: ['pane', 'Almanac'],
  launchpad: ['pane', 'Launchpad'],
  polaroid: ['tool', 'Polaroid'],
  warden: ['guard', 'Warden'],
  ballast: ['guard', 'Ballast'],
  thrift: ['guard', 'Thrift'],
}

const ORDER = ['hub', 'pane', 'band', 'transcript', 'companion', 'status', 'sound', 'guard', 'tool', 'extra']

const only = (process.env.KOZMOS_ONLY ?? '').split(',').map(s => s.trim()).filter(Boolean)
const mods = readdirSync(join(root, 'mods'))
  .filter(m => existsSync(join(root, 'mods', m, '.claude-plugin', 'plugin.json')))
  .filter(m => !only.length || only.includes(m))
  .map(m => {
    const p = JSON.parse(readFileSync(join(root, 'mods', m, '.claude-plugin', 'plugin.json'), 'utf8'))
    const [category, title] = META[m] ?? ['extra', m]
    // "KOZMOS Title: blurb. More." → "blurb." (first sentence after the colon).
    const after = String(p.description ?? '').replace(/^KOZMOS[^:]*:\s*/, '')
    const blurb = (after.match(/^.*?[.!?](\s|$)/)?.[0] ?? after).trim()
    return { name: p.name, version: p.version ?? '0.1.0', description: p.description ?? '', category, title, blurb }
  })
  .sort((a, b) => ORDER.indexOf(a.category) - ORDER.indexOf(b.category) || a.name.localeCompare(b.name))

const marketplace = {
  name: 'kozmos',
  owner: { name: 'Ersin Koç', url: 'https://github.com/ersinkoc' },
  metadata: { description: 'KOZMOS: a bundle of live, visual Claude Code mods — bands above the prompt, sidebars, a status ticker, companions and sound.' },
  plugins: mods.map(m => ({ name: m.name, source: `./mods/${m.name}`, description: m.description, version: m.version, category: m.category })),
}
mkdirSync(join(root, '.claude-plugin'), { recursive: true })
writeFileSync(join(root, '.claude-plugin', 'marketplace.json'), JSON.stringify(marketplace, null, 2) + '\n')

const hub = join(root, 'mods', 'kozmos', 'hooks')
if (existsSync(hub)) {
  const rows = mods
    .filter(m => m.name !== 'kozmos')
    .map(m => `  { name: ${JSON.stringify(m.name)}, title: ${JSON.stringify(m.title)}, category: ${JSON.stringify(m.category)}, blurb: ${JSON.stringify(m.blurb)} },`)
  writeFileSync(
    join(hub, 'catalog.ts'),
    `// GENERATED by scripts/build-catalog.mjs from every mod's plugin.json. Do not edit.\n\n` +
      `export type Category = 'pane' | 'band' | 'transcript' | 'companion' | 'status' | 'sound' | 'guard' | 'tool' | 'extra'\n` +
      `export type CatalogEntry = { name: string; title: string; category: Category; blurb: string }\n\n` +
      `export const CATALOG: readonly CatalogEntry[] = [\n${rows.join('\n')}\n]\n`,
  )
}
console.log(`catalog: ${mods.length} mods → marketplace.json${existsSync(hub) ? ' + kozmos/hooks/catalog.ts' : ''}`)
