// Writes the mods section of README.md (between the gallery markers) from
// .claude-plugin/marketplace.json and the images in docs/previews/:
// a section per category, and per mod its command, what it does, and its
// terminal and desktop pictures (the desktop one in the reader's theme).
//   node scripts/build-readme.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const prev = join(root, 'docs', 'previews')
const { plugins } = JSON.parse(readFileSync(join(root, '.claude-plugin', 'marketplace.json'), 'utf8'))

const SECTIONS = [
  ['hub', 'Hub', 'One command opens them all.'],
  ['pane', 'Sidebars', 'Docked beside the transcript; each toggles with its own command.'],
  ['band', 'Bands above the prompt — the visual show', 'Live drawings just above the chat input. Every band has a ✕ and its command brings it back.'],
  ['transcript', 'Transcript and spinner', 'Small, tasteful additions to what Claude Code already draws.'],
  ['companion', 'Companions', 'A little life around the work.'],
  ['status', 'Status line', ''],
  ['sound', 'Sound', 'Synthesized here, no samples. The engine plays audio on macOS and the desktop app.'],
  ['guard', 'Guards', 'Watch the risky moments and step in.'],
  ['tool', 'Tools', ''],
]
// The component a mod's picture shows, when it draws several.
const PRIMARY = ['pane', 'aboveprompt', 'spinner', 'turnduration', 'prompthint', 'tooluse', 'toolgroup']

const blurbOf = d => d.replace(/^KOZMOS [^:]*:\s*/, '')
const titleOf = n => n.charAt(0).toUpperCase() + n.slice(1)

function shotsOf(name) {
  for (const c of PRIMARY) {
    const term = `${name}-${c}-terminal.png`
    const light = `${name}-${c}-desktop-light.png`
    const dark = `${name}-${c}-desktop-dark.png`
    if (existsSync(join(prev, term)) || existsSync(join(prev, dark))) {
      return { term: existsSync(join(prev, term)) ? term : null, light: existsSync(join(prev, light)) ? light : null, dark: existsSync(join(prev, dark)) ? dark : null }
    }
  }
  return null
}

const img = (f, alt, w) => `<img src="docs/previews/${f}" alt="${alt}" width="${w}">`
function desktop(s, alt, w) {
  if (!s.dark && !s.light) return ''
  if (s.dark && s.light) {
    return `<picture><source media="(prefers-color-scheme: dark)" srcset="docs/previews/${s.dark}"><img src="docs/previews/${s.light}" alt="${alt}" width="${w}"></picture>`
  }
  return img(s.dark ?? s.light, alt, w)
}

let out = ''
let count = 0
for (const [cat, heading, intro] of SECTIONS) {
  const mods = plugins.filter(p => p.category === cat)
  if (!mods.length) continue
  out += `\n### ${heading}\n\n${intro ? intro + '\n\n' : ''}`
  for (const m of mods) {
    count++
    const s = shotsOf(m.name)
    out += `#### ${titleOf(m.name)} · \`/${m.name}\`\n\n${blurbOf(m.description)}\n\n`
    if (s) {
      const isPane = cat === 'pane' || cat === 'hub'
      if (isPane) {
        // Sidebars: terminal and desktop side by side.
        out += `<table><tr><td valign="top">${s.term ? img(s.term, `${m.name} in the terminal`, 520) : ''}</td><td valign="top">${desktop(s, `${m.name} in the desktop app`, 300)}</td></tr></table>\n\n`
      } else {
        // Bands: wide, one under the other.
        if (s.term) out += `${img(s.term, `${m.name} in the terminal`, 820)}\n\n`
        const d = desktop(s, `${m.name} in the desktop app`, 820)
        if (d) out += `<details><summary>Desktop app</summary>\n\n${d}\n\n</details>\n\n`
      }
    }
  }
}

const readme = readFileSync(join(root, 'README.md'), 'utf8')
const START = '<!-- gallery:start -->'
const END = '<!-- gallery:end -->'
if (!readme.includes(START)) throw new Error('README.md has no gallery markers')
const next = readme.slice(0, readme.indexOf(START) + START.length) + `\n<!-- Generated by scripts/build-readme.mjs. Edit the mods' plugin.json descriptions instead. -->\n${out}\n` + readme.slice(readme.indexOf(END))
writeFileSync(join(root, 'README.md'), next.replace(/\{\{COUNT\}\}/g, String(plugins.length)))
console.log(`README gallery: ${count} mods`)
