// Test coverage for the mods: statements, branches, functions and lines.
//   node scripts/coverage.mjs [mod ...] [--json out.json] [--quiet]
//
// `claude plugin test` has no coverage of its own, so this measures it:
//  1. copies each mod to .kozmos/cov/<mod> and instruments every hooks file
//     with istanbul counters (the shared kit as shared/kz.ts and shared/probe.ts);
//  2. wraps the mod's register so a hidden `/__kzcov` command answers with the
//     counters of the mod's own realm, where its hooks run;
//  3. points the tests' 'claude-code/testing' import at a shim whose `test`
//     asks for those counters when each test ends, and prints them with the
//     counters of the test's realm (code a test imports directly);
//  4. merges every test's counters and reports per file.
// The shared kit is measured across all the mods run together.
import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync, cpSync, statSync } from 'node:fs'
import { join, dirname, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createInstrumenter } from 'istanbul-lib-instrument'
import libCoverage from 'istanbul-lib-coverage'
import { transformSync } from '@babel/core'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const isWin = process.platform === 'win32'
const posix = p => p.split(sep).join('/')
const args = process.argv.slice(2)
const flag = (name) => { const i = args.indexOf(name); if (i < 0) return undefined; const v = args[i + 1]; args.splice(i, 2); return v }
const jsonOut = flag('--json')
const quiet = args.includes('--quiet') ? (args.splice(args.indexOf('--quiet'), 1), true) : false
const all = readdirSync(join(root, 'mods')).filter(m => existsSync(join(root, 'mods', m, '.claude-plugin', 'plugin.json')))
const mods = args.length ? args : all
const SHARED = new Set(['kz.ts', 'probe.ts'])

const instrumenter = createInstrumenter({
  esModules: true,
  compact: false,
  coverageGlobalScope: 'globalThis',
  coverageGlobalScopeFunc: false,
  parserPlugins: ['typescript', 'jsx', 'importAttributes'],
  produceSourceMap: false,
})

const SHIM = `// GENERATED by scripts/coverage.mjs: 'claude-code/testing' with a \`test\`
// that prints the coverage counters when each test ends.
import { test as kzTest } from 'claude-code/testing'
export * from 'claude-code/testing'
const RUN = { origin: { kind: 'composer' as const }, presentation: { isFullscreen: true, columns: 160 } }
export const test = (name: string, ...rest: any[]) => {
  const body = rest[rest.length - 1]
  const wrapped = async ($: any, on: any) => {
    try {
      return await body($, on)
    } finally {
      try {
        const r = await $.command.run({ command: '__kzcov', args: '', ...RUN })
        console.log('KZCOV ' + (r?.text ?? '{}'))
      } catch (err) {
        console.log('KZCOVERR ' + String(err))
      }
      console.log('KZCOV ' + JSON.stringify((globalThis as any).__coverage__ ?? {}))
    }
  }
  return rest.length > 1 ? (kzTest as any)(name, rest[0], wrapped) : (kzTest as any)(name, wrapped)
}
`
const DUMP = `
// Added by scripts/coverage.mjs: /__kzcov answers with this realm's counters.
export const register: Register = (on, options) => {
  on('command.run', { command: '__kzcov' }, () => ({ text: JSON.stringify((globalThis as { __coverage__?: unknown }).__coverage__ ?? {}) }))
  return __kzRegister(on, options)
}
`

function walk(dir, out = []) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f)
    if (statSync(p).isDirectory()) walk(p, out)
    else out.push(p)
  }
  return out
}

// The engine reads a module's atoms, $ calls and hooks by their shape, so a
// counter istanbul folds into a declaration, `const a = (cov().s[2]++, atom(..))`,
// moves out in front of it as its own statement: `cov().s[2]++; const a = atom(..)`.
const isCounter = (n) => n?.type === 'UpdateExpression' && /^cov_/.test(rootName(n.argument))
const rootName = (n) => (n?.type === 'MemberExpression' ? rootName(n.object) : n?.type === 'CallExpression' ? rootName(n.callee) : n?.type === 'Identifier' ? n.name : '')
function hoistCounters({ types: t }) {
  return {
    visitor: {
      VariableDeclaration(path) {
        if (!Array.isArray(path.container)) return
        const pre = []
        for (const d of path.node.declarations) {
          const init = d.init
          if (init?.type === 'SequenceExpression' && init.expressions.length === 2 && isCounter(init.expressions[0])) {
            pre.push(t.expressionStatement(init.expressions[0]))
            d.init = init.expressions[1]
          }
        }
        if (pre.length) path.insertBefore(pre)
      },
    },
  }
}
function instrument(code, filename) {
  const out = instrumenter.instrumentSync(code, filename)
  return transformSync(out, {
    filename: filename.replace(/\.ts$/, '.tsx'),
    babelrc: false, configFile: false, compact: false, retainLines: false,
    parserOpts: { plugins: ['typescript', 'jsx', 'importAttributes'] },
    plugins: [hoistCounters],
  }).code
}

const map = libCoverage.createCoverageMap({})
const results = []
for (const mod of mods) {
  const src = join(root, 'mods', mod)
  const dst = join(root, '.kozmos', 'cov', mod)
  rmSync(dst, { recursive: true, force: true })
  mkdirSync(dst, { recursive: true })
  cpSync(src, dst, { recursive: true, filter: s => !posix(s).includes('/.claude-plugin/types') })
  // Instrument the hooks.
  for (const file of walk(join(dst, 'hooks'))) {
    if (!/\.tsx?$/.test(file) || file.endsWith('.d.ts')) continue
    const rel = posix(relative(dst, file))
    const base = rel.split('/').pop()
    const isShared = rel.startsWith('hooks/lib/') && SHARED.has(base)
    const origin = isShared ? `shared/${base}` : `mods/${mod}/${rel}`
    const code = readFileSync(join(root, origin), 'utf8')
    let out = instrument(code, join(root, origin))
    if (rel === 'hooks/register.tsx' || rel === 'hooks/register.ts') {
      const re = /export const register(\s*:\s*Register)?\s*=/
      if (!re.test(out)) throw new Error(`${mod}: no "export const register" to wrap`)
      out = out.replace(re, 'const __kzRegister$1 =') + DUMP
    }
    writeFileSync(file, out)
  }
  // Point the tests at the shim.
  const tests = existsSync(join(dst, 'tests')) ? walk(join(dst, 'tests')).filter(f => /\.test\.tsx?$/.test(f)) : []
  writeFileSync(join(dst, 'tests', '__kzcov.ts'), SHIM)
  for (const t of tests) {
    const relShim = posix(relative(dirname(t), join(dst, 'tests', '__kzcov.ts'))).replace(/\.ts$/, '')
    const s = readFileSync(t, 'utf8').replace(/from 'claude-code\/testing'/g, (m, i, all) => {
      // Type-only imports can stay; value imports go through the shim.
      const line = all.slice(all.lastIndexOf('\n', i) + 1, i)
      return line.startsWith('import type') ? m : `from '${relShim.startsWith('.') ? relShim : './' + relShim}'`
    })
    writeFileSync(t, s)
  }
  const r = spawnSync('claude', ['plugin', 'test', posix(relative(root, dst))], { cwd: root, encoding: 'utf8', shell: isWin, maxBuffer: 512 * 1024 * 1024 })
  const text = `${r.stdout}${r.stderr}`
  let dumps = 0
  for (const line of text.split('\n')) {
    if (line.startsWith('KZCOV ')) {
      const data = JSON.parse(line.slice(6))
      if (Object.keys(data).length) { map.merge(data); dumps++ }
    }
  }
  const pass = Number(/(\d+) pass/.exec(text)?.[1] ?? 0)
  const fail = Number(/(\d+) fail/.exec(text)?.[1] ?? 0)
  const errs = text.split('\n').filter(l => l.startsWith('KZCOVERR')).length
  results.push({ mod, pass, fail, dumps, errs, exit: r.status })
  if (!quiet) console.log(`${mod}: ${pass} pass, ${fail} fail${errs ? `, ${errs} dump errors` : ''}${fail || r.status ? '\n' + text.split('\n').filter(l => !l.startsWith('KZCOV')).slice(-25).join('\n') : ''}`)
}

// Report, per file: the four percentages and what is left uncovered.
const pct = (c, t) => (t ? (100 * c) / t : 100)
const files = []
for (const f of map.files()) {
  const fc = map.fileCoverageFor(f)
  const s = fc.toSummary()
  const rel = posix(relative(root, f))
  // A mod's run covers only its own files and the shared kit.
  const owner = rel.startsWith('mods/') ? rel.split('/')[1] : null
  if (owner && !mods.includes(owner)) continue
  const lines = fc.getUncoveredLines().map(Number)
  const ranges = []
  for (const n of lines) { const last = ranges[ranges.length - 1]; if (last && n === last[1] + 1) last[1] = n; else ranges.push([n, n]) }
  const bm = fc.branchMap, b = fc.b
  const branches = []
  for (const id of Object.keys(b)) b[id].forEach((hits, k) => { if (!hits) { const at = bm[id].locations?.[k]; const loc = at?.start?.line != null ? at : bm[id].loc; branches.push(`${loc.start.line}:${bm[id].type}#${k}`) } })
  const fns = Object.keys(fc.f).filter(id => !fc.f[id]).map(id => `${fc.fnMap[id].name}@${fc.fnMap[id].loc.start.line}`)
  files.push({
    file: rel,
    statements: s.statements.pct, branches: s.branches.pct, functions: s.functions.pct, lines: s.lines.pct,
    uncoveredLines: ranges.map(([a, z]) => (a === z ? `${a}` : `${a}-${z}`)).join(','),
    uncoveredBranches: branches, uncoveredFunctions: fns,
  })
}
files.sort((a, z) => a.file.localeCompare(z.file))
const total = map.getCoverageSummary()
const totals = { statements: total.statements.pct, branches: total.branches.pct, functions: total.functions.pct, lines: total.lines.pct }
const fmt = n => (typeof n === 'number' ? n.toFixed(1).padStart(5) : '  n/a')
console.log('\nfile                                            stmts  branch  funcs  lines  uncovered lines')
for (const f of files) {
  const full = f.statements === 100 && f.branches === 100 && f.functions === 100 && f.lines === 100
  console.log(`${full ? '✓' : '✗'} ${f.file.padEnd(46)} ${fmt(f.statements)}  ${fmt(f.branches)}  ${fmt(f.functions)}  ${fmt(f.lines)}  ${f.uncoveredLines.slice(0, 80)}`)
}
console.log(`\nall                                             ${fmt(totals.statements)}  ${fmt(totals.branches)}  ${fmt(totals.functions)}  ${fmt(totals.lines)}`)
const failing = results.filter(r => r.fail || r.exit)
console.log(`tests: ${results.reduce((a, r) => a + r.pass, 0)} pass, ${results.reduce((a, r) => a + r.fail, 0)} fail across ${results.length} mods${failing.length ? ` (failing: ${failing.map(r => r.mod).join(', ')})` : ''}`)
if (jsonOut) writeFileSync(jsonOut, JSON.stringify({ totals, results, files }, null, 2))
const isFull = files.every(f => f.statements === 100 && f.branches === 100 && f.functions === 100 && f.lines === 100)
process.exit(failing.length || !isFull ? 1 : 0)
