// Copies shared/*.ts (kz.ts, probe.ts) into every mod's hooks/lib/.
// A hooks module may import only files inside its own plugin, so each mod
// carries its own copy; this keeps them identical.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const files = ['kz.ts', 'probe.ts']
const header = f => `// GENERATED by scripts/sync-shared.mjs from shared/${f}. Do not edit here.
`
let n = 0
for (const mod of readdirSync(join(root, 'mods'))) {
  const hooks = join(root, 'mods', mod, 'hooks')
  if (!existsSync(hooks)) continue
  mkdirSync(join(hooks, 'lib'), { recursive: true })
  for (const f of files) writeFileSync(join(hooks, 'lib', f), header(f) + readFileSync(join(root, 'shared', f), 'utf8'))
  n++
}
console.log(`shared kit synced into ${n} mods`)
