// GENERATED by scripts/build-catalog.mjs from every mod's plugin.json. Do not edit.

export type Category = 'pane' | 'band' | 'transcript' | 'companion' | 'status' | 'sound' | 'guard' | 'tool' | 'extra'
export type CatalogEntry = { name: string; title: string; category: Category; blurb: string }

export const CATALOG: readonly CatalogEntry[] = [
  { name: "breadcrumbs", title: "Breadcrumbs", category: "pane", blurb: "the session's web trail in a sidebar." },
  { name: "bridge", title: "Bridge", category: "pane", blurb: "a mission-control sidebar." },
  { name: "chronicle", title: "Chronicle", category: "pane", blurb: "the session as a timeline." },
  { name: "faultline", title: "Faultline", category: "pane", blurb: "the error lens in a sidebar." },
  { name: "gearbox", title: "Gearbox", category: "pane", blurb: "tool analytics for the session." },
  { name: "gitscope", title: "Gitscope", category: "pane", blurb: "a git radar sidebar." },
  { name: "hivemind", title: "Hivemind", category: "pane", blurb: "the agent swarm as a live tree." },
  { name: "hourglass", title: "Hourglass", category: "pane", blurb: "the limit oracle." },
  { name: "mosaic", title: "Mosaic", category: "pane", blurb: "a GitHub-style activity calendar across sessions." },
  { name: "relay", title: "Relay", category: "pane", blurb: "the API latency lab in a sidebar." },
  { name: "spectra", title: "Spectra", category: "pane", blurb: "the context X-ray." },
  { name: "switchboard", title: "Switchboard", category: "pane", blurb: "an MCP observatory sidebar." },
  { name: "taskforge", title: "Taskforge", category: "pane", blurb: "a live kanban of the session's tasks." },
  { name: "terminus", title: "Terminus", category: "pane", blurb: "the session's shell history in a sidebar." },
  { name: "thermal", title: "Thermal", category: "pane", blurb: "a heatmap of the files this session touches." },
  { name: "tokenomics", title: "Tokenomics", category: "pane", blurb: "the cost lab." },
  { name: "vitals", title: "Vitals", category: "pane", blurb: "a btop-style machine monitor sidebar." },
  { name: "aurora", title: "Aurora", category: "band", blurb: "northern lights above the prompt while the model thinks." },
  { name: "glyphfall", title: "Glyphfall", category: "band", blurb: "matrix rain of tool activity above the prompt while Claude works." },
  { name: "heartline", title: "Heartline", category: "band", blurb: "a neon EKG of the session drawn above the prompt." },
  { name: "orrery", title: "Orrery", category: "band", blurb: "subagents as planets circling a central sun above the prompt." },
  { name: "compass", title: "Compass", category: "transcript", blurb: "the single most useful hint under the prompt." },
  { name: "mantra", title: "Mantra", category: "transcript", blurb: "a themed spinner." },
  { name: "stamp", title: "Stamp", category: "transcript", blurb: "a receipt on every finished turn." },
  { name: "toolmarks", title: "Toolmarks", category: "transcript", blurb: "badges on tool rows." },
  { name: "marquee", title: "Marquee", category: "status", blurb: "a status-line ticker." },
  { name: "ballast", title: "Ballast", category: "guard", blurb: "a context coach." },
  { name: "thrift", title: "Thrift", category: "guard", blurb: "a frugal mode." },
  { name: "warden", title: "Warden", category: "guard", blurb: "a guard for destructive shell commands." },
]
