// GENERATED by scripts/build-catalog.mjs from every mod's plugin.json. Do not edit.

export type Category = 'pane' | 'band' | 'transcript' | 'companion' | 'status' | 'sound' | 'guard' | 'tool' | 'extra'
export type CatalogEntry = { name: string; title: string; category: Category; blurb: string }

export const CATALOG: readonly CatalogEntry[] = [
  { name: "bridge", title: "Bridge", category: "pane", blurb: "a mission-control sidebar." },
]
